using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using CsvHelper;

namespace CSV_Reader_for_Database
{

    public class TheDataTables
    {

        public TheDataTables()
        {
        DataTable DTAcctLog = new DataTable("AcctLog");
            DTAcctLog.Columns.Add("unique_id", typeof(int));
            DTAcctLog.Columns.Add("repuid", typeof(int));
            DTAcctLog.Columns.Add("memid", typeof(int));
            DTAcctLog.Columns.Add("start_time", typeof(DateTime));
            DTAcctLog.Columns.Add("endtime", typeof(DateTime));
            DTAcctLog.Columns.Add("Module", typeof(char));
            DTAcctLog.Columns.Add("numchanged", typeof(int));
        DataTable DTAppointment = new DataTable("Appointment");
        DataTable DTAppointmentMembers = new DataTable("AppointmentMembers");
        DataTable DTAppointmentReps = new DataTable("AppointmentReps");
        DataTable DTAppointmentType = new DataTable("AppointmentType");
        DataTable DTAppTrack = new DataTable("AppTrack");
        DataTable DTAppts = new DataTable("Appts");
        DataTable DTARBalances = new DataTable("ARBalances");
        DataTable DTBankFile = new DataTable("DTBankFile");
        DataTable DTBCheck = new DataTable("BCheck");
        DataTable DTBigIntField = new DataTable("BigIntField");
        DataTable DTBillDOM = new DataTable("BillDOM");
        DataTable DTBLOB = new DataTable("BLOB");
        DataTable DTCancelRule = new DataTable("CancelRule");
        DataTable DTCardList = new DataTable("CardList");
        DataTable DTChargeTally = new DataTable("ChargeTally");
        DataTable DTCHRGCode = new DataTable("CHRGCode");
        DataTable DTClass = new DataTable("Class");
        DataTable DTClassCodes = new DataTable("ClassCodes");
        DataTable DTClassType = new DataTable("ClassType");
        DataTable DTCodes = new DataTable("Codes");
        DataTable DTCodes2 = new DataTable("Codes2");
        DataTable DTCollChanges = new DataTable("CollChanges");
        DataTable DTCollPay = new DataTable("CollPay");
        DataTable DTCompany = new DataTable("Company");
        DataTable DTComparisonReports = new DataTable("ComparisonReports");
        DataTable DTContractMember = new DataTable("ContractMember");
        DataTable DTContracts = new DataTable("Contracts");
        DataTable DTCtcCodes = new DataTable("CtcCodes");
        DataTable DTCustomEmail = new DataTable("CustomEmail");
        DataTable DTCycBill = new DataTable("CycBill");
        DataTable DTDeletedReps = new DataTable("DeletedReps");
        DataTable DTDeltaChargeTally = new DataTable("DeltaChargeTally");
        DataTable DTDigitalCalcTokens = new DataTable("DigitalCalcTokens");
        DataTable DTDigitalContractLabels = new DataTable("DigitalContractLabels");
        DataTable DTDigitalContracts = new DataTable("DigitalContracts");
        DataTable DTDigitalCustomTokens = new DataTable("DigitalCustomTokens");
        DataTable DTDigitalPrefillContract = new DataTable("DigitalPrefillContract");
        DataTable DTDigitalPrefills = new DataTable("DigitalPrefills");
        DataTable DTDigitalPrefillTokens = new DataTable("DigitalPrefillTokens");
        DataTable DTDoorTypes = new DataTable("DoorTypes");
        DataTable DTDtrans = new DataTable("DTrans");
        DataTable DTEfts = new DataTable("Efts");
        DataTable DTEftsBatch = new DataTable("EftsBatch");
        DataTable DTEmergency = new DataTable("Emergency");
        DataTable DTEmpDept = new DataTable("EmpDept");
        DataTable DTErrLog = new DataTable("ErrLog");
        DataTable DTEventDtrans = new DataTable("EventDTrans");
        DataTable DTEventHDTrans = new DataTable("EventHDTrans");
        DataTable DTEventOnAcct = new DataTable("EventOnAcct");
        DataTable DTFlag = new DataTable("Flag");
        DataTable DTFRAWARDED = new DataTable("FRAWARDED");
        DataTable DTFRRules = new DataTable("FRRules");
        DataTable DTGifts = new DataTable("Gifts");
        DataTable DTGiftTrans = new DataTable("GiftTrans");
        DataTable DTHDTrans = new DataTable("HDTrans");
        DataTable DTIAdjust = new DataTable("IAdjust");
        DataTable DTInOut = new DataTable("InOut");
        DataTable DTIntegerField = new DataTable("IntegerField");
        DataTable DTLocate = new DataTable("Locate");
        DataTable DTLocateTable = new DataTable("LocateTable");
        DataTable DTLockers = new DataTable("Lockers");
        DataTable DTLog = new DataTable("Log");
        DataTable DTLogFile = new DataTable("LogFile");
        DataTable DTLogInOutLog = new DataTable("LogInOutLog");
        DataTable DTMailsu = new DataTable("Mailsu");
        DataTable DTMemberCard = new DataTable("MemberCard");
        DataTable DTMemberContracts = new DataTable("MemberContracts");
        DataTable DTMembers = new DataTable("Members");
        DataTable DTMemberTransaction = new DataTable("MemberTransaction");
        DataTable DTMemMisc = new DataTable("MemMisc");
        DataTable DTMemPasswordArchive = new DataTable("MemPasswordArchive");
        DataTable DTMempix = new DataTable("Mempix");
        DataTable DTMemuse = new DataTable("Memuse");
        DataTable DTMergeDocuments = new DataTable("MergeDocuments");
        DataTable DTMergeExtra = new DataTable("MergeExtra");
        DataTable DTMergeFilters = new DataTable("MergeFilters");
        DataTable DTMergeTokens = new DataTable("MergeTokens");
        DataTable DTMobilinkUser = new DataTable("MobilinkUser");
        DataTable DTMPHIS = new DataTable("MPHIS");
        DataTable DTOnAcct = new DataTable("OnAcct");
        DataTable DTPBCatCol = new DataTable("PBCatCol");
        DataTable DTPBCatEdt = new DataTable("PBCatEdt");
        DataTable DTPBCatFmt = new DataTable("PBCatFmt");
        DataTable DTPBCattbl = new DataTable("PBCattbl");
        DataTable DTPBCatvld = new DataTable("PBCatvld");
        DataTable DTPCCRESP = new DataTable("PCCResp");
        DataTable DTPccSetup = new DataTable("PccSetup");
        DataTable DTPCCTrans = new DataTable("PCCTrans");
        DataTable DTPendingCycle = new DataTable("PendingCycle");
        DataTable DTPendingFamily = new DataTable("PendingFamily");
        DataTable DTPendingMembers = new DataTable("PendingMembers");
        DataTable DTPendingToken = new DataTable("PendingToken");
        DataTable DTPendingTokenAction = new DataTable("PendingTokenAction");
        DataTable DTPendingTokenType = new DataTable("PendingTokenType");
        DataTable DTPFFrontDeskStats = new DataTable("PFFrontDeskStats");
        DataTable DTPFTouchScreenButtons = new DataTable("TouchScreenButtons");
        DataTable DTPoS = new DataTable("PoS");
        DataTable DTPoSShift = new DataTable("PoSShift");
        DataTable DTPostFile = new DataTable("PostFile");
        DataTable DTRanges = new DataTable("Ranges");
        DataTable DTRates = new DataTable("Rates");
        DataTable DTRecurringClose = new DataTable("RecurringClose");
        DataTable DTReferral = new DataTable("Referral");
        DataTable DTRegisterCodes = new DataTable("RegisterCodes");
        DataTable DTRemDoors = new DataTable("RemDoors");
        DataTable DTRemJobs = new DataTable("RemJobs");
        DataTable DTRemports = new DataTable("Remports");
        DataTable DTReportSaves = new DataTable("ReportSaves");
        DataTable DTRepPassword = new DataTable("RepPassword");
        DataTable DTReps = new DataTable("Reps");
        DataTable DTRepTasks = new DataTable("RepTasks");
        DataTable DTRetPPost = new DataTable("RetPPost");
        DataTable DTRights = new DataTable("Rights");
        DataTable DTRoom = new DataTable("Room");
        DataTable DTRoomClose = new DataTable("RoomClose");
        DataTable DTRoomCodes = new DataTable("RoomCodes");
        DataTable DTRoomHours = new DataTable("RoomHours");
        DataTable DTRoomType = new DataTable("RoomType");
        DataTable DTRuleClass = new DataTable("RuleClass");
        DataTable DTRuleLocation = new DataTable("RuleLocation");
        DataTable DTRules = new DataTable("Rules");
        DataTable DTSalesAnalysis = new DataTable("SalesAnalysis");
        DataTable DTSalesReportingCategory = new DataTable("SalesReprtingCategory");
        DataTable DTSentList = new DataTable("SentList");
        DataTable DTSeries = new DataTable("Series");
        DataTable DTSPCard = new DataTable("SPCard");
        DataTable DTStatistics = new DataTable("Statistics");
        DataTable DTStringField = new DataTable("StringField");
        DataTable DTTabApptTypes = new DataTable("TabApptTypes");
        DataTable DTTabRoomTypes = new DataTable("TabRoomTypes");
        DataTable DTTabs = new DataTable("Tabs");
        DataTable DTTabTrainers = new DataTable("TabTrainers");
        DataTable DTTanningBeds = new DataTable("TanningBeds");
        DataTable DTTanningUse = new DataTable("TanningUse");
        DataTable DTTasks = new DataTable("Tasks");
        DataTable DTTrainerCode = new DataTable("TrainerCode");
        DataTable DTTrainerSchedule = new DataTable("TrainerSchedule");
        DataTable DTUpdates = new DataTable("Updates");
        DataTable DTUseType = new DataTable("UseType");
        DataTable DTVendor = new DataTable("Vendor");
        DataTable DTWaitList = new DataTable("WaitList");
        DataTable DTWorkout = new DataTable("Workout");
        DataTable DTXref = new DataTable("Xref");
        DataTable DTXrefClub = new DataTable("XrefClub");
        DataTable DTZipCode = new DataTable("ZipCode");
        }

        //*****************************************************DataTable workTable = new DataTable("Customers");

        //DataColumn workCol = workTable.Columns.Add("CustID", typeof(Int32));
        //workCol.AllowDBNull = false;
        //workCol.Unique = true;

        //workTable.Columns.Add("CustLName", typeof(String));
        //workTable.Columns.Add("CustFName", typeof(String));
        //workTable.Columns.Add("Purchases", typeof(Double));***************************************************************
    }
}
